export const COLORES_ECOMMERCE_PRODUCTOS = [
    { nombre: "Amarillo", valor: "#FFD700" },
    { nombre: "Azul Pacífico", valor: "#1CA9C9" },
    { nombre: "Negro", valor: "#000000" },
    { nombre: "Rosa", valor: "#FF69B4" },
    { nombre: "Titanio Azul", valor: "#0F4C81" },
    { nombre: "Titanio Natural", valor: "#D6D6D6" },
    { nombre: "Titanio Negro", valor: "#1C1C1C" },
    { nombre: "Crema", valor: "#FFFDD0" },
    { nombre: "Violeta", valor: "#8A2BE2" },
    { nombre: "Gris Titanio", valor: "#7E7E7E" },
    { nombre: "Gris Espacial", valor: "#4B4B4B" },
    { nombre: "Negro Titanio", valor: "#141414" },
    { nombre: "Violeta Titanio", valor: "#6A5ACD" },
    { nombre: "Obsidiana", valor: "#0B0B0B" },
    { nombre: "Verde", valor: "#228B22" },
    { nombre: "Blanco", valor: "#FFFFFF" },
    { nombre: "Dorado", valor: "#FFD700" },
    { nombre: "Gris Espacial", valor: "#4B4B4B" },
    { nombre: "Oro", valor: "#DAA520" },
    { nombre: "Plata", valor: "#C0C0C0" },
    { nombre: "Gris", valor: "#808080" },
    { nombre: "Azul", valor: "#434F69" },
    { nombre: "Platino", valor: "#E5E4E2" },
    { nombre: "Beige", valor: "#F5F5DC" },
    { nombre: "Graphite", valor: "#383838" },
    { nombre: "Negro (Digital)", valor: "#000000" },
    { nombre: "Blanco (Series S)", valor: "#FFFFFF" },
    { nombre: "Neón", valor: "#39FF14" },
    { nombre: "Medianoche", valor: "#191970" },
    { nombre: "Titanio", valor: "#8D8D8D" },
    { nombre: "Antracita", valor: "#2F4F4F" },
    { nombre: "Tiza", valor: "#EDEDED" },
    { nombre: "Rojo", valor: "#FE0000" },

];
